server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/turing_academy_db
    username: postgres
    password: Ali200aa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
