spring:
  datasource:
    url: jdbc:postgresql://dpg-cvjis5a4d50c73a8ast0-a:5432/turing_academy_db
    username: turing_academy_db_user
    password: USTI05hfADGlYx3WusAuwHMD17cGDilf
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
